<?php
//
// File generated by PowerERP installer 17.0.2 on 06 Août 2023
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$powererp_main_url_root='http://localhost/powererp-17.0.2/htdocs';
$powererp_main_document_root='C:/laragon/www/PowerERP-17.0.2/htdocs';
$powererp_main_url_root_alt='/custom';
$powererp_main_document_root_alt='C:/laragon/www/PowerERP-17.0.2/htdocs/custom';
$powererp_main_data_root='C:/laragon/www/PowerERP-17.0.2/documents';
$powererp_main_db_host='localhost';
$powererp_main_db_port='3306';
$powererp_main_db_name='powererp-17';
$powererp_main_db_prefix='llx_';
$powererp_main_db_user='root';
$powererp_main_db_pass='';
$powererp_main_db_type='mysqli';
$powererp_main_db_character_set='utf8';
$powererp_main_db_collation='utf8_unicode_ci';
// Authentication settings
$powererp_main_authentication='powererp';

//$powererp_main_demo='autologin,autopass';
// Security settings
$powererp_main_prod='0';
$powererp_main_force_https='0';
$powererp_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$powererp_nocsrfcheck='0';
$powererp_main_instance_unique_id='9177bbed877aaa1806d3eda539a3f27f';
$powererp_mailing_limit_sendbyweb='0';
$powererp_mailing_limit_sendbycli='0';

//$powererp_lib_FPDF_PATH='';
//$powererp_lib_TCPDF_PATH='';
//$powererp_lib_FPDI_PATH='';
//$powererp_lib_TCPDI_PATH='';
//$powererp_lib_GEOIP_PATH='';
//$powererp_lib_NUSOAP_PATH='';
//$powererp_lib_ODTPHP_PATH='';
//$powererp_lib_ODTPHP_PATHTOPCLZIP='';
//$powererp_js_CKEDITOR='';
//$powererp_js_JQUERY='';
//$powererp_js_JQUERY_UI='';

//$powererp_font_DOL_DEFAULT_TTF='';
//$powererp_font_DOL_DEFAULT_TTF_BOLD='';
$powererp_main_distrib='standard';
